let maior = Math.max(5,10,15,20,25,30);
console.log (maior);
let menor = Math.min(1,2,3,4,5,6,7);
console.log (menor);
let arredondabaixo = Math.round (6.49);
console.log (arredondabaixo);
let arredondacima = Math.round (6.50);
console.log (arredondacima);
let arredondaparacimasempre = Math.ceil (5.20);
console.log (arredondaparacimasempre);